### ISSUE TITLE
 Unexpected Drops in Energy Production and Income Readings Throughout the Day

### ISSUE THREAD

**Issue by candycab** [UtilitechAS/amsreader-firmware#807]
Description:
I am experiencing unexpected drops in the energy production and income readings throughout the day using the AMS reader. 
There are sudden drops in the values before they increase again. This issue occurs intermittently and affects the accuracy of the data displayed in Home Assistant.

Steps to Reproduce:
Set up the AMS reader with the latest firmware version.
Configure MQTT settings as per the documentation.
Observe the energy production and income readings in Home Assistant throughout the day.

Expected Behavior:
The energy production and income readings should increase steadily throughout the day without sudden drops.

![Skjermbilde 2024-06-13 190715](https://github.com/UtilitechAS/amsreader-firmware/assets/34286669/db92b16c-7456-4648-aeae-0ad5f0d47bca)
![Skjermbilde 2024-06-13 190734](https://github.com/UtilitechAS/amsreader-firmware/assets/34286669/d6a41e66-7c17-4541-b691-3653aedb801e)

Hardware information:
 - Country: Norway
 - Meter: Kamstrup
 - AMS reader: ESP8266, Pow-K

**Relevant firmware information:**
 - Version: 2.3.5
 - MQTT: yes

**Comment by wknutsen** [comment]
I think this is fixed in next version. and is related to bug #788

**Comment by ArnieO** [comment]
v2.3.6 is right around the corner now! 
Expected later today if nothing unexpected shows up.

**Comment by gskjold** [comment]
2.3.6 is out, but it looks to me like your device reboots a lot

**Comment by candycab** [comment]
I'm still experiencing problems despite upgrading to version 2.3.6. 
@gskjold You mentioned that the device restarts frequently—how did you determine this?
![Skjermbilde 2024-06-30 141859](https://github.com/UtilitechAS/amsreader-firmware/assets/34286669/1ba7d105-9352-4b85-a5f6-61d7d03abe1a)
![Skjermbilde 2024-06-30 141913](https://github.com/UtilitechAS/amsreader-firmware/assets/34286669/43d7f4aa-96e5-436b-a63a-98bf838ef9d7)
![Skjermbilde 2024-06-30 142148](https://github.com/UtilitechAS/amsreader-firmware/assets/34286669/32bacc0a-fbfe-4ff8-97b2-7cc0fbd493e9)

**Comment by ArnieO** [comment]
> I'm still experiencing problems despite upgrading to version 2.3.6.
@gskjold You mentioned that the device restarts frequently—how did you determine this?

Power meters with "HAN NVE" configuration sends accumulated energy (kWh) only once per hour (at whole hour). 
Such drops are usually an indication that the the device reboots in between those messages, as the firmware makes a running estimate/accumulation of kWh based on power readings. If device reboots, that estimate is restarted. When passing whole hour, kWh is reset to the value reported by the meter - and the curve jumps back up.

However, it does not look like your device is rebooting often; "Up 4 days":
![image](https://github.com/UtilitechAS/amsreader-firmware/assets/10295178/3a4babe0-7db4-4b4f-a8a6-6fb52af11460)

We are starting to see some unexpected issues with the old ESP8266 devices, see for instance https://github.com/UtilitechAS/amsreader-firmware/issues/815
If you too have made a "long" upgrade I would try a Factory reset as I proposed in that thread. 
I would also try to disable MQTT as a test - and observe if there are drops in the Consumption figures in the "Real time calculation" tile.

We currently do not have an "upgrade to ESP32" system - but that might be a good idea. When did you buy your Pow-K?

**Comment by ArnieO** [comment]
You may want to try the test firmware posted here: https://github.com/UtilitechAS/amsreader-firmware/issues/815#issuecomment-2199477693
